### ISSUE TITLE
PDI to Starting Configuration

### ISSUE THREAD

**Issue by RainierBarrett** [cmelab/uli-init#1]
From our meeting with Chris C and Jessie, it would be nice to be able to just plug in the values for PDI (M_w and M_n), fit a distribution of molecular weights to them, and initialize the system by sampling from that.

**Comment by chrisjonesBSU** [comment]
I was thinking of an approach where the inputs would be the mode (majority polymer length) and a desired PDI value that determines the width of the distribution that we sample from.  

I'm not really sure how defining the weight average initial before generating the system would work.  It would more so be a result of the sampling from the distribution.

 https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html
So if we used numpy we could define the mean, scale and size.
