### ISSUE TITLE
Set up a CI tool

### ISSUE THREAD

**Issue by chrisjonesBSU** [cmelab/uli-init#10]
It would be nice to have a CI tool in place.  @jennyfothergill said she will help with this in a couple weeks : )

**Comment by chrisjonesBSU** [comment]
Lets stick with github actions.  Once we have some unit tests in place I'll get going with this.

**Comment by jennyfothergill** [comment]
@chrisjonesBSU I'm ready to help anytime! c:

**Comment by chrisjonesBSU** [comment]
Closing thanks to Jenny :)
