### ISSUE TITLE
installing via environment-dev throws error

### ISSUE THREAD

**Issue by jennyfothergill** [cmelab/uli-init#33]
We need to add hoomd, I think 2.9.4 is best because it fixes a thrust issue with installation on gpu
Also gsd

**Comment by chrisjonesBSU** [comment]
Well, the installation instructions list the hoomd install as a separate step.  I'm not sure if any issues would come up with hoomd being installed via anaconda, but then wanting to use a compiled hoomd when submitting jobs on Fry. Until there is a GPU image for ULI, I don't know if putting hoomd in the `.yml` file is a good idea.

**Comment by jennyfothergill** [comment]
Ah! OK, that makes sense. I gotta read those instruction better huh 😅

**Comment by chrisjonesBSU** [comment]
I think was fixed with the addition of the -nohoomd yml file.
